### ISSUE TITLE
Content of working directory will be lost if umount fails

### ISSUE THREAD

**Issue by rzarzynski** [c0d3z3r0/armdebootstrap#1]
Errors from underlying call to the `umount` utility are silently ignored (line [172](https://github.com/c0d3z3r0/armdebootstrap/blob/master/armdebootstrap.py#L172) and [173](https://github.com/c0d3z3r0/armdebootstrap/blob/master/armdebootstrap.py#L173)). The problem is clearly visible on Debian Wheezy and similar distributions where `umount` doesn't support `-R` option.

Moreover, `tempfile.TemporaryDirectory` class doesn't seem to be right choice for management of working directory. The directory will be deleted even if the `sys.exit` is called.

```
$ LC_ALL=C umount --help
Usage: umount -h | -V
       umount -a [-d] [-f] [-r] [-n] [-v] [-t vfstypes] [-O opts]
       umount [-d] [-f] [-r] [-n] [-v] special | node...
$ cat /etc/debian_version 
7.8
```

**Comment by c0d3z3r0** [comment]
Thank you :)

umount -R is now replaced by explicit unmount of each partition and the script now uses tempfile.mkdtemp instead of TemporaryDirectory.

**Comment by rzarzynski** [comment]
Thanks a lot! :-)
